# Fichier _config.yml pour Jekyll
title: "Mon Site Jekyll avec Hugo Relearn"
description: "Une brève description de votre site"
baseurl: "" # le sous-chemin de votre site, par exemple /blog
url: "https://420SN1RE.github.io/A24" # l'URL de votre site

# Paramètres GitHub Pages
repository: "420SN1RE/A24" # nom du dépôt GitHub

# Thème
theme: "hugo-relearn"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-seo-tag

# Paramètres du thème Hugo Relearn
relearn:
  author: "Nathalie Desmangles"
  showReadingTime: true
  description: "Programmation en sciences"

