baseURL = 'https://example.org/'
languageCode = 'fr-ca'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

theme = 'hugo-theme-relearn'

disableLandingPageButton = true

[params]
  search = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  identifier = "home"
  hidden = true

